# reproduce
seed: 2026

# model
vocab_size: 32 # 32
d_model: 64 # 64
ff_dim: 256
num_heads: 1
num_layers: 1000

# TF model variants
linear_attn: False
residual: True
mlp: False
dropout: 0.1
norm: True
output_norm: False
trainable_norm: False
pos: "rotary"
rotary_theta: 10000

# training
max_seq_len: 64
device: "cpu"